# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

##########################################################################################
#                   Task to get the cluster report from the primary instance             #
#                 after all the test cases have been executed.                           #
##########################################################################################
- name:                                 "Get the cluster status"
  become:                               true
  get_cluster_status_db:
    db_instance_number:                 "{{ db_instance_number }}"
    operation_step:                     "cluster_report_collection"
    database_sid:                       "{{ db_sid | lower | default('') }}"
    saphanasr_provider:                 "{{ saphanasr_provider | default('SAPHanaSR') }}"
  register:                             cluster_status
  failed_when:                          cluster_status.primary_node == ""

- name:                                 "Get the cluster report from the primary node"
  become:                               true
  run_once:                             true
  when:
                                        - cluster_status is defined
                                        - cluster_status.primary_node == ansible_hostname
  block:
    - name:                             "Cluster report from the HA cluster"
      ansible.builtin.command:          "{{ commands | selectattr('name', 'equalto', 'crm_report_cmd') | map(attribute=(ansible_os_family | upper)) | first }}"
      register:                         cluster_report_results
      failed_when:                      cluster_report_results.rc != 0

    - name:                             "Copy the cluster report to the local machine"
      ansible.builtin.fetch:
        src:                            "/tmp/{{ test_group_invocation_id }}.{{ item }}"
        dest:                           "{{ _workspace_directory }}/logs/cluster_report/"
        flat:                           true
      changed_when:                     false
      register:                         copy_cluster_report
      ignore_errors:                    true
      with_items:
                                        - "tar.bz2"
                                        - "tar.gz"

    - name:                             "Remove the cluster report from the primary node"
      ansible.builtin.file:
        state:                          absent
        path:                           "/tmp/{{ test_group_invocation_id }}.{{ item }}"
      register:                         remove_cluster_report
      ignore_errors:                    true
      with_items:
                                        - "tar.bz2"
                                        - "tar.gz"
