# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

####################################################################################
#                     Render HTML report from the test results                     #
####################################################################################

- name:                                 "Create HTML report and upload it to storage account"
  run_once:                             true
  delegate_to:                          localhost
  block:
    - name:                             "Load HTML jinja2 template"
      no_log:                           true
      ansible.builtin.set_fact:
        html_report_template:           "{{ lookup('file', html_template_name | default('./templates/report.html')) }}"

    - name:                             "Get framework version"
      no_log:                           true
      ansible.builtin.set_fact:
        framework_version:              "{{ lookup('file', '../../../../VERSION') | default('unknown') }}"

    - name:                             "Read the log file and create a HTML report"
      render_html_report:
        test_group_invocation_id:       "{{ test_group_invocation_id }}"
        test_group_name:                "{{ report_file_name | default(test_group_name + '_' + ansible_os_family | upper) }}"
        report_template:                "{{ html_report_template }}"
        workspace_directory:            "{{ _workspace_directory }}"
        test_case_results:              "{{ all_results | default([]) }}"
        system_info:                    "{{ system_info | default({}) }}"
        framework_version:              "{{ framework_version | default('unknown') }}"
      register:                         report_file_path
