# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

################################################################################
#                Rescue tasks for the test cases                               #
################################################################################

- name:                                 "Read var log messages by importing role"
  ansible.builtin.include_tasks:        "roles/misc/tasks/var-log-messages.yml"

- name:                                 "Post Validations: HA cluster status after test execution"
  block:
    - name:                             "Validate cluster_status_pre exists"
      ansible.builtin.set_fact:
        cluster_status_pre:             "{{ cluster_status_pre | default({}) }}"

    - name:                             "Set first_node variable"
      ansible.builtin.set_fact:
        first_node: >-
          {{
            cluster_status_pre.primary_node | default(
              cluster_status_pre.ascs_node | default(
                ansible_play_hosts | first
              )
            )
          }}

    - name:                              "Set second_node variable"
      ansible.builtin.set_fact:
        second_node: >-
          {{
            cluster_status_pre.secondary_node | default(
              cluster_status_pre.ers_node | default(
                (ansible_play_hosts | difference([first_node]))[0] | default(first_node)
              )
            )
          }}

    - name:                             "Merge and sort logs from all nodes by timestamp"
      delegate_to:                      localhost
      log_parser:
        function:                       "merge_logs"
        logs:
          - "{{ hostvars[first_node]['var_log_messages_output'].filtered_logs | default('[]') }}"
          - "{{ hostvars[second_node]['var_log_messages_output'].filtered_logs | default('[]') }}"
      register:                         merged_logs_output

    - name:                           "Set combined logs variable"
      ansible.builtin.set_fact:
        combined_logs:                "{{ merged_logs_output.filtered_logs | from_json }}"

    - name:                             "Post Validations: Rescure operation set test case status"
      delegate_to:                      localhost
      ansible.builtin.set_fact:
        test_case_name:                 "{{ item.name }}: {{ test_execution_hostname | default(inventory_hostname) }}"
        test_case_hostname:             "{{ virtual_host | default(inventory_hostname) }}"
        test_case_description:          "{{ item.description }}"
        test_case_status:               "FAILED"
        test_case_message:              "{{ ansible_failed_result | default('Unknown error occurred') }}"
        test_case_details:              "{{ ansible_failed_result | default('No error details available')}}"
        test_case_var_log_messages:     "{{ combined_logs | default([]) }}"

- name:                                 "Post Telemetry Data"
  ansible.builtin.include_tasks:        "roles/misc/tasks/post-telemetry-data.yml"
  run_once:                             true
