enums:
  severity:
    - info:                           &info "INFO"
    - high:                           &high "HIGH"
    - low:                            &low "LOW"
    - warning:                        &warning "WARNING"
    - critical:                       &critical "CRITICAL"
    - all_severity:                   &severity [*info, *high, *low, *warning, *critical]

  os_type:
    - suse:                           &suse "SLES_SAP"
    - redhat:                         &redhat "REDHAT"
    - oraclelinux:                    &oraclelinux "OracleLinux"
    - windows:                        &windows "Windows"
    - all_os:                         &os_type [*suse, *redhat, *oraclelinux, *windows]

  os_version:
    - suse_12_3:                      &suse_12_3 "SUSE 12 SP3"
    - suse_12_4:                      &suse_12_4 "SUSE 12 SP4"
    - suse_12_5:                      &suse_12_5 "SUSE 12 SP5"
    - all_versions:                   &all_versions "all"

  hardware_type:
    - vm:                             &vm "VM"
    - hli:                            &hli "HLI"
    - all_hardware:                   &all_hardware [*vm, *hli]

  storage_type:
    premium_storage:                  &premium_storage ["Premium_LRS","UltraSSD_LRS","ANF","PremiumV2_LRS","AFS"]
    anf:                              &anf ["ANF"]
    all_storage:                      &all_storage ["Premium_LRS","UltraSSD_LRS","StandardSSD_LRS","Standard_LRS","ANF","PremiumV2_LRS","AFS"]

  workload:
    - sap:                            &sap "SAP"
    - all_workload:                   &workload [*sap]

  db:
    - hana:                           &hana "HANA"
    - mssql:                          &mssql "MSSQL"
    - oracle:                         &oracle "Oracle"
    - db2:                            &db2 "Db2"
    - ase:                            &ase "ASE"
    - all_db:                         &db [*hana, *mssql, *oracle, *db2, *ase]

  role:
    - db:                             &db_role "DB"
    - ascs:                           &ascs_role "SCS"
    - ers:                            &ers_role "ERS"
    - app:                            &app_role "APP"
    - webdispatcher:                  &web_dispatch "WEB"
    - pas:                            &pas "PAS"
    - all_role:                       &role [*db_role, *ascs_role, *ers_role, *app_role, *web_dispatch, *pas]

  cluster_type:
    - sbd:                            &sbd "ISCSI"
    - fencing_agent:                  &fencing_agent "AFA"
    - all_fencing_agent:              &cluster_type [*sbd, *fencing_agent]

  high_availability:
    - no_ha:                         &no_high_availability "false"
    - scale_up:                      &scale_up "scale_up"
    - scale_out:                     &scale_out "scale_out"
    - all_ha:                        &high_availability [*scale_up, *scale_out]

  collector_type:
    - command:                        &command "command"
    - azure:                          &azure "azure"
    - all_collector_type:             &collector_type [*command, *azure]

  category:
    - package:                        &package_check "Package"
    - vm:                             &vm_check "Virtual Machine"
    - sap:                            &sap_check "SAP"
    - os:                             &os_check "Operating System"
    - all_check_types:                &category [*package_check, *vm_check, *sap_check, *os_check]

  user:
    - root:                           &root "root"
    - sidadm:                         &sidadm "sidadm"
    - all_users:                      &user [*root, *sidadm]

  validator_type:
    - string:                         &string "string"
    - range:                          &range "range"
    - list:                           &list "list"
    - all:                            &validator_type [*string, *range, *list]

  report:
    - check:                          &check "check"
    - section:                        &section "section"
    - table:                          &table "table"
    - report:                         &report [*check, *section]

checks:
  - id:                                 "ASCS-0001"
    name:                               "Load Balancer timestamps"
    description:                        "Timestamp parameter for HA Load Balancers"
    category:                           *sap_check
    severity:                           *high
    workload:                           *sap
    applicability:
      os_type:                        [*suse, *redhat]
      os_version:                     *all_versions
      hardware_type:                  *vm
      storage_type:                   *all_storage
      role:                           [*ascs_role, *db_role]
      database_type:                  *db
      high_availability:              *scale_up
      high_availability_agent:        *cluster_type
    collector_type:                     *command
    collector_args:
      command:                          "/sbin/sysctl net.ipv4.tcp_timestamps -n"
    validator_type:                     *string
    validator_args:
      expected_output:                  "0"
    report:                             *check

  - id:                                 "ASCS-0002"
    name:                               "Filesystem Mount Points"
    description:                        "Lists all mounted filesystems and their types to ensure SAP HANA directories are configured with supported filesystems."
    category:                           *sap_check
    severity:                           *info
    workload:                           *sap
    applicability:
      os_type:                          [*suse, *redhat]
      os_version:                       *all_versions
      hardware_type:                    *vm
      storage_type:                     *all_storage
      role:                             [*ascs_role, *ers_role]
    collector_type:                     *azure
    collector_args:
      resource_type:                    "filesystem"
    report:                             *table
    references:
      sap:                              "2972496"
      microsoft:                        "https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage"

  - id:                                 "ASCS-0003"
    name:                               "Azure Disks"
    description:                        "Lists all attached Azure disks to ensure SAP HANA directories are configured with supported disks."
    category:                           *sap_check
    severity:                           *info
    workload:                           *sap
    applicability:
      os_type:                          [*suse, *redhat]
      os_version:                       *all_versions
      hardware_type:                    *vm
      storage_type:                     *all_storage
      role:                             [*ascs_role, *ers_role]
    collector_type:                     *azure
    collector_args:
      resource_type:                    "azure_disks"
    report:                             *table
    references:
      sap:                              "2972496"
      microsoft:                        "https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage"

  - id:                                 "ASCS-0004"
    name:                               "LVM Groups"
    description:                        "Lists all LVM groups to ensure ASCS directories are configured with supported LVM configurations."
    category:                           *sap_check
    severity:                           *info
    workload:                           *sap
    applicability:
      os_type:                          [*suse, *redhat]
      os_version:                       *all_versions
      hardware_type:                    *vm
      storage_type:                     *all_storage
      role:                             [*ascs_role, *ers_role]
    collector_type:                     *azure
    collector_args:
      resource_type:                    "lvm_groups"
    report:                             *table
    references:
      sap:                              "2972496"
      microsoft:                        "https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage"

  - id:                                 "ASCS-0005"
    name:                               "LVM Volumes"
    description:                        "Lists all LVM volumes to ensure ASCS directories are configured with supported LVM configurations."
    category:                           *sap_check
    severity:                           *info
    workload:                           *sap
    applicability:
      os_type:                          [*suse, *redhat]
      os_version:                       *all_versions
      hardware_type:                    *vm
      storage_type:                     *all_storage
      role:                             [*ascs_role, *ers_role]
    collector_type:                     *azure
    collector_args:
      resource_type:                    "lvm_volumes"
    report:                             *table
    references:
      sap:                              "2972496"
      microsoft:                        "https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage"

  - id:                                 "ASCS-0006"
    name:                               "ANF Volumes"
    description:                        "Lists all ANF volumes to ensure ASCS directories are configured with supported ANF configurations."
    category:                           *sap_check
    severity:                           *info
    workload:                           *sap
    applicability:
      os_type:                          [*suse, *redhat]
      os_version:                       *all_versions
      hardware_type:                    *vm
      storage_type:                     *all_storage
      role:                             [*ascs_role, *ers_role]
    collector_type:                     *azure
    collector_args:
      resource_type:                    "anf_volumes"
    report:                             *table
    references:
      sap:                              "2972496"
      microsoft:                        "https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-vm-operations-storage"
