# Enumeration definitions
enums:
  severity:
    - info:                           &info "INFO"
    - high:                           &high "HIGH"
    - low:                            &low "LOW"
    - warning:                        &warning "WARNING"
    - critical:                       &critical "CRITICAL"
    - all_severity:                   &severity [*info, *high, *low, *warning, *critical]

  os_type:
    - suse:                           &suse "SUSE"
    - redhat:                         &redhat "REDHAT"
    - oraclelinux:                    &oraclelinux "OracleLinux"
    - windows:                        &windows "Windows"
    - all_os:                         &os_type [*suse, *redhat, *oraclelinux, *windows]

  os_version:
    - suse_12_3:                      &suse_12_3 "SUSE 12 SP3"
    - suse_12_4:                      &suse_12_4 "SUSE 12 SP4"
    - suse_12_5:                      &suse_12_5 "SUSE 12 SP5"
    - all_versions:                   &all_versions "all"

  hardware_type:
    - vm:                             &vm "VM"
    - hli:                            &hli "HLI"
    - all_hardware:                   &all_hardware [*vm, *hli]

  storage_type:
    premium_storage:                  &premium_storage ["Premium_LRS","UltraSSD_LRS","ANF","PremiumV2_LRS","AFS"]
    anf:                              &anf ["ANF"]

  workload:
    - sap:                            &sap "SAP"
    - all_workload:                   &workload [*sap]

  db:
    - hana:                           &hana "HANA"
    - mssql:                          &mssql "MSSQL"
    - oracle:                         &oracle "Oracle"
    - db2:                            &db2 "Db2"
    - ase:                            &ase "ASE"
    - all_db:                         &db [*hana, *mssql, *oracle, *db2, *ase]

  role:
    - db:                             &db_role "DB"
    - ascs:                           &ascs_role "SCS"
    - ers:                            &ers_role "ERS"
    - app:                            &app_role "APP"
    - webdispatcher:                  &web_dispatch "WEB"
    - pas:                            &pas "PAS"
    - all_role:                       &role [*db_role, *ascs_role, *ers_role, *app_role, *web_dispatch, *pas]

  cluster_type:
    - sbd:                            &sbd "ISCSI"
    - fencing_agent:                  &fencing_agent "AFA"
    - all_fencing_agent:              &cluster_type [*sbd, *fencing_agent]

  collector_type:
    - command:                        &command "command"
    - azure:                          &azure "azure"
    - all_collector_type:             &collector_type [*command, *azure]

  category:
    - package:                        &package_check "Package"
    - vm:                             &vm_check "Virtual Machine"
    - load_balancer:                  &load_balancer_check "Load Balancer"
    - sap:                            &sap_check "SAP"
    - os:                             &os_check "Operating System"
    - all_check_types:                &category [*package_check, *vm_check, *sap_check, *os_check]

  user:
    - root:                           &root "root"
    - sidadm:                         &sidadm "sidadm"
    - all_users:                      &user [*root, *sidadm]

  validator_type:
    - string:                         &string "string"
    - range:                          &range "range"
    - list:                           &list "list"
    - all:                            &validator_type [*string, *range, *list]

  report:
    - check:                          &check "check"
    - section:                        &section "section"
    - report:                         &report [*check, *section]

checks:
  - id:                               "IC-0040"
    name:                             "Load Balancers Idle Timeout"
    description:                      "Checks the idle timeout of the load balancers"
    category:                         *load_balancer_check
    severity:                         *high
    workload:                         *workload
    applicability:
      os_type:                        [*suse, *redhat, *oraclelinux, *windows]
      os_version:                     *all_versions
      hardware_type:                  *vm
      role:                           *role
      database_type:                  *db
    collector_type:                   *azure
    collector_args:
      command:                        |-
                                      load_balancer_id=$(az network lb show
                                        --resource-group {{ CONTEXT.resource_group_name }}
                                        --name {{ CONTEXT.vm_name }}
                                        --query "id" -o tsv);
                                      if [ -z "$load_balancer_id" ] || [ "$load_balancer_id" == "null" ]; then
                                        echo "No Load Balancer defined";
                                      else
                                        echo "$load_balancer_id";
                                      fi
    validator_type:                   *string
    validator_args:
      expected_output:                "No Load Balancer defined"
      properties:
        - name:                       "Idle Timeout"
          property:                   "idletimeout"
          type:                       *string
          value:                      "30"
        - name:                       "Floating IP"
          property:                   "floatingip"
          type:                       *string
          value:                      "false"
        - name:                       "Protocols"
          property:                   "protocols"
          type:                       *string
          value:                      "All"
        - name:                       "Probe Interval"
          property:                   "probeinterval"
          type:                       *string
          value:                      "15"
        - name:                       "Probe Threshold"
          property:                   "ProbeThreshold"
          type:                       *string
          value:                      "2"
    report:                           *check
