# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------
# |                     Kill Enqueue Server Process                           |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: SCS Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-scs.yml"

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Kill Enqueue Server Process"
  become:                               true
  when:                                 pre_validations_status == "PASSED"
  block:
    - name:                             "Test Execution: Kill Enqueue Server on ASCS Node"
      when:                             ansible_hostname == cluster_status_pre.ascs_node
      become:                           true
      block:
        - name:                         "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.ascs_node].ansible_hostname }}"

        - name:                         "Test Execution: Check for ENSA version"
          ansible.builtin.shell:        pgrep -f 'enq.sap{{ sap_sid | upper }}'
          register:                     ensa2_check
          failed_when:                  false

        - name:                         "Test Execution: Kill Enqueue Server Process (ENSA1)"
          ansible.builtin.shell:        set -o pipefail && pgrep -f 'en.sap{{ sap_sid | upper }}' | xargs kill -9
          register:                     kill_er_result
          failed_when:                  false
          when:                         ensa2_check.stdout == ""

        - name:                         "Test Execution: Kill Enqueue Server Process (ENSA2)"
          ansible.builtin.shell:        set -o pipefail && pgrep -f 'enq.sap{{ sap_sid | upper }}' | xargs kill -9
          register:                     kill_en_result
          failed_when:                  false
          when:                         ensa2_check.stdout != ""

        - name:                         "Test Execution: Validate ASCS node has stopped"
          get_cluster_status_scs:
            sap_sid:                    "{{ sap_sid | lower }}"
          register:                     cluster_status_test_execution_pre
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until:                        cluster_status_test_execution_pre.ascs_node == ""

        - name:                         "Test Execution: Cleanup resources"
          ansible.builtin.command:      crm_resource --cleanup
          register:                     cleanup_failed_resource_test_execution
          changed_when:                 cleanup_failed_resource_test_execution.rc == 0

        - name:                         "Test Execution: Validate SCS cluster status for ENSA1"
          when:                         ensa2_check.stdout == "0"
          get_cluster_status_scs:
            sap_sid:                    "{{ sap_sid | lower }}"
          register:                     cluster_status_test_execution
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_test_execution.ascs_node == cluster_status_pre.ers_node
                                        and cluster_status_test_execution.ers_node == cluster_status_pre.ascs_node

        - name:                         "Test Execution: Validate SCS cluster status for ENSA2"
          when:                         ensa2_check.stdout != "0"
          get_cluster_status_scs:
            sap_sid:                    "{{ sap_sid | lower }}"
          register:                     cluster_status_test_execution
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        (cluster_status_test_execution.ascs_node == cluster_status_pre.ers_node
                                        and cluster_status_test_execution.ers_node == cluster_status_pre.ascs_node)
                                        or (cluster_status_test_execution.ascs_node == cluster_status_pre.ascs_node
                                        and cluster_status_test_execution.ers_node == cluster_status_pre.ers_node)

        - name:                         "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: |
                                        ENSA Version: {{ "ENSA1" if ensa2_check.stdout == "0" else "ENSA2" }}
                                        Old ASCS: {{ cluster_status_pre.ascs_node }}
                                        New ASCS: {{ cluster_status_test_execution.ascs_node }}
                                        Old ERS: {{ cluster_status_pre.ers_node }}
                                        New ERS: {{ cluster_status_test_execution.ers_node }}
            test_case_details_from_test_case: {
                                        "Pre Validations: Validate SCS cluster status": "{{ cluster_status_pre }}",
                                        "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                        "Test Execution: Kill Enqueue Server Process": "{{ kill_en_result }}",
                                        "Test Execution: Cleanup resources": "{{ cleanup_failed_resource_test_execution }}",
                                        "Post Validations Result": "{{ cluster_status_test_execution }}",
                                        }
# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"

- name:                                 "Pre Validations: Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for SCS cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Validate SCS cluster status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
