# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |                          Manual resource migration                        |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Manual resource migration"
  become:                               true
  when:                                 node_tier == "hana"
  block:
    - name:                             "Test Execution: Manual resource migration init"
      when:
                                        - pre_validations_status == "PASSED"
                                        - ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.primary_node].ansible_hostname }}"

        - name:                         "Test Execution: Get HANA resource id for saphanasr_angi"
          when:                         saphanasr_provider | default('SAPHanaSR') == "SAPHanaSR-angi"
          block:
            - name:                     "Test Execution: Get HANA resource id for saphanasr_angi"
              ansible.builtin.shell: >-
                                        set -o pipefail && {{ commands
                                          | selectattr('name','equalto','get_hana_resource_id_saphanasr_angi')
                                          | map(attribute=(ansible_os_family|upper))
                                          | first
                                        }}
              args:
                executable:             /bin/bash
              changed_when:             false
              register:                 hana_clone_resource_id
              failed_when:              hana_clone_resource_id.rc != 0

            - name:                     "Test Execution: Set fact the hana_clone_resource_name"
              ansible.builtin.set_fact:
                hana_clone_resource_name:     "{{ hana_clone_resource_id.stdout }}"

        - name:                         "Test Execution: Get HANA resource id"
          when:                         saphanasr_provider | default('SAPHanaSR') == "SAPHanaSR"
          block:
            - name:                     "Try master resource ID"
              ansible.builtin.shell: >-
                                        set -o pipefail && {{ commands
                                          | selectattr('name','equalto','get_hana_clone_resource_id')
                                          | map(attribute=(ansible_os_family|upper))
                                          | first
                                        }}
              args:
                executable:             /bin/bash
              changed_when:             false
              register:                 hana_clone_resource_id
              failed_when:              hana_clone_resource_id.rc != 0
          rescue:
            - name:                     "Try clone resource ID"
              ansible.builtin.shell: >-
                                        set -o pipefail && {{ commands
                                          | selectattr('name','equalto','get_hana_clone_resource_id')
                                          | map(attribute='REDHAT')
                                          | first
                                        }}
              args:
                executable:             /bin/bash
              changed_when:             false
              register:                 hana_clone_resource_id
              failed_when:              hana_clone_resource_id.rc != 0
              ignore_errors:            true
          always:
            - name:                     "Test Execution: Set the resource name"
              when:
                                        - hana_clone_resource_id.rc == 0
                                        - hana_clone_resource_id.stdout is defined
                                        - hana_clone_resource_id.stdout | type_debug != 'NoneType'
                                        - hana_clone_resource_id.stdout | trim | length > 1
              ansible.builtin.set_fact:
                hana_clone_resource_name: "{{ hana_clone_resource_id.stdout }}"

        - name:                         "Test Execution: Move the resource to the targeted node"
          ansible.builtin.command:      "{{ commands | selectattr(
                                        'name', 'equalto', 'resource_migration_cmd') | map(
                                        attribute=(ansible_os_family | upper)) | first }}"
          register:                     hana_db_resource_migration
          failed_when:                  hana_db_resource_migration.rc != 0
          changed_when:                 hana_db_resource_migration.rc == 0

        - name:                         "Test Execution: Validate HANA DB cluster status 1"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
          register:                     cluster_status_test_execution
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          failed_when:                  false
          until: |
                                        cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node
                                        and cluster_status_test_execution.secondary_node == ""

        - name:                         "Test Execution: Register Failed Resource when automated_register is false"
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "false"
          block:
            - name:                     "Test Execution: Set facts for the failed resource"
              ansible.builtin.set_fact:
                replication_mode:       "{{ cluster_status_pre.replication_mode }}"
                primary_site_name:      "{{ cluster_status_pre.primary_site_name }}"
                operation_mode:         "{{ cluster_status_pre.operation_mode }}"

            - name:                     "Test Execution: Register the failed resource"
              become:                   true
              become_user:              "{{ db_sid | lower }}adm"
              ansible.builtin.shell: |
                                        source /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number | upper }}/HDBSettings.sh && \
                                        /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe/hdbnsutil -sr_register \
                                        --remoteHost={{ cluster_status_pre.secondary_node }} \
                                        --remoteInstance={{ db_instance_number }} \
                                        --replicationMode={{ replication_mode }} \
                                        --name={{ primary_site_name }} \
                                        --operationMode={{ operation_mode }} --online
              register:                 hana_db_register_failed_resource
              args:
                executable:             /bin/bash

            - name:                     "Pre Validation: CleanUp any failed resource"
              become:                   true
              ansible.builtin.command:  crm_resource --cleanup
              ignore_errors:            true
              register:                 cleanup_failed_resource_post

        - name:                         "Test Execution: Remove any location_constraints"
          location_constraints:
            action:                     "remove"
          register:                     location_constraints_result

        # This is required because the cluster reports incorrect location constraints
        # after the location constraints is removed.
        - name:                         "Test Execution: Wait for 100 seconds"
          ansible.builtin.wait_for:
            timeout:                    100

        - name:                         "Test Execution: Validate HANA DB cluster status 2"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
          register:                     cluster_status_test_execution_1
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_test_execution_1.primary_node == cluster_status_pre.secondary_node and
                                        cluster_status_test_execution_1.secondary_node == cluster_status_pre.primary_node

        - name:                         "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: "Old primary: {{ cluster_status_pre.primary_node }} \
                                          New primary: {{ cluster_status_test_execution_1.primary_node }} \
                                          Old secondary: {{ cluster_status_pre.secondary_node }} \
                                          New secondary: {{ cluster_status_test_execution_1.secondary_node }}"
            test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                          "Test Execution: Resource Migration": "{{ hana_db_resource_migration }}",
                                          "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_test_execution_1 }}",
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"

- name:                                 "Pre Validations: Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for HANA DB cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                          "Cluster Status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
