# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |               Kill SBD Inquisitor                                         |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  when:                                 database_cluster_type == "ISCSI"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: HANA DB Nodes"
  when:                                 database_cluster_type == "ISCSI"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: SBD Inquisitor kill"
  become:                               true
  when:
                                        - node_tier == "hana"
                                        - database_cluster_type == "ISCSI"
                                        - pre_validations_status == "PASSED"
                                        - cluster_status_pre.stonith_action == "reboot"
  block:
    - name:                             "Test Execution: SBD Inquisitor kill init"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.primary_node].ansible_hostname }}"

        - name:                         "Test Execution:  Find the port of inquisitor process"
          become:                       true
          ansible.builtin.shell: |
                                        set -o pipefail
                                        pgrep -f 'sbd: inquisitor' | head -n 1
          register:                     inquisitor_port
          failed_when:                  inquisitor_port.rc != 0

        - name:                         "Test Execution: Kill the inquisitor process"
          become:                       true
          ansible.builtin.shell:        "kill -9 {{ inquisitor_port.stdout }}"
          async:                        1
          poll:                         0
          register:                     inquisitor_kill

    - name:                             "Test Execution: Wait for the failover to happen"
      when:                             ansible_hostname == cluster_status_pre.secondary_node
      block:
        - name:                         "Test Execution: Validate HANA DB cluster status during stop operation."
          when:                         cluster_status_pre.AUTOMATED_REGISTER == "true"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          register:                     cluster_status_test_execution
          until: |
                                        cluster_status_test_execution.primary_node == cluster_status_pre.secondary_node and
                                        cluster_status_test_execution.secondary_node == cluster_status_pre.primary_node

    - name:                             "Test Execution: SBD Inquisitor kill manual fail over"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Validate HANA DB cluster status 2"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
            hana_clone_resource_name:   "{{ hana_clone_resource_name | default('') }}"
            hana_primitive_resource_name: "{{ hana_primitive_resource_name | default('') }}"
          register:                     cluster_status_test_post
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_test_post.primary_node == cluster_status_pre.secondary_node and
                                        cluster_status_test_post.secondary_node == cluster_status_pre.primary_node

        - name:                         "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: "Old primary: {{ cluster_status_pre.primary_node }} \
                                        New primary: {{ cluster_status_test_post.primary_node }} \
                                        Old secondary: {{ cluster_status_pre.secondary_node }} \
                                        New secondary: {{ cluster_status_test_post.secondary_node }}"
            test_case_details_from_test_case: {
                                        "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                        "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                        "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                        "Test Execution: Kill inquisitor results": "{{ inquisitor_kill }}",
                                        "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_test_post }}",
                                        }

# /*---------------------------------------------------------------------------
# |                          Post Validations                                 |
# +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"

- name:                                 "Pre Validations: Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for HANA DB cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                          "Cluster Status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
