# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------
# |               Crash Index Server on the Secondary Instance                |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Setup Tasks"
  ansible.builtin.include_tasks:        "roles/misc/tasks/test-case-setup.yml"
  run_once:                             true

# /*---------------------------------------------------------------------------
# |                          Pre Validations                                  |
# +--------------------------------------------------------------------------*/
- name:                                 "Pre Validations: HANA DB Nodes"
  ansible.builtin.include_tasks:        "roles/misc/tasks/pre-validations-db.yml"

- name:                                 "Pre Validations: Check if indexserver process is enabled"
  become:                               true
  check_indexserver:
    database_sid:                       "{{ db_sid | upper }}"
  register:                             index_server_check

# /*---------------------------------------------------------------------------
# |                          Test Execution                                   |
# +--------------------------------------------------------------------------*/
- name:                                 "Test Execution: Crash Index Server"
  become:                               true
  when:
                                        - node_tier == "hana"
                                        - pre_validations_status == "PASSED"
                                        - cluster_status_pre.stonith_action == "reboot"
                                        - index_server_check.indexserver_enabled == "yes"
  block:
    - name:                             "Test Execution: Crash Index Server init"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Start timer"
          ansible.builtin.set_fact:
            test_execution_start:       "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"
            test_execution_hostname:    "{{ hostvars[cluster_status_pre.secondary_node].ansible_hostname }}"

    - name:                             "Test Execution: Validate HANA DB cluster status"
      when:                             ansible_hostname == cluster_status_pre.secondary_node
      block:
        - name:                         "Test Execution: Crash the index server on secondary node"
          ansible.builtin.command:      "killall -9 hdbindexserver"
          register:                     index_server_result
          changed_when:                 index_server_result.rc == 0
          failed_when:                  index_server_result.rc != 0

    - name:                             "Test Execution: Crash the index server cont"
      when:                             ansible_hostname == cluster_status_pre.primary_node
      block:
        - name:                         "Test Execution: Validate HANA DB cluster status"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "test_execution"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
          register:                     cluster_status_test_execution
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_test_execution.primary_node == cluster_status_pre.primary_node and
                                        cluster_status_test_execution.secondary_node == ""

        - name:                         "Test Execution: Validate HANA DB cluster status 2"
          get_cluster_status_db:
            db_instance_number:         "{{ db_instance_number }}"
            operation_step:             "post_failover"
            database_sid:               "{{ db_sid | lower }}"
            saphanasr_provider:         "{{ saphanasr_provider | default('SAPHanaSR') }}"
          register:                     cluster_status_post
          retries:                      "{{ default_retries }}"
          delay:                        "{{ default_delay }}"
          until: |
                                        cluster_status_post.primary_node == cluster_status_pre.primary_node and
                                        cluster_status_post.secondary_node == cluster_status_pre.secondary_node

        - name:                         "Test Execution: CleanUp any failed resource"
          ansible.builtin.command:      crm_resource --cleanup
          register:                     cleanup_failed_resource_post
          changed_when:                 cleanup_failed_resource_post.rc == 0
          ignore_errors:                true

        - name:                         "Test Execution: Stop timer"
          ansible.builtin.set_fact:
            test_execution_end:         "{{ now(utc=true, fmt='%Y-%m-%d %H:%M:%S') }}"

        - name:                         "Set test case message and details"
          ansible.builtin.set_fact:
            test_case_message_from_test_case: |
                                        "Old primary: {{ cluster_status_pre.primary_node }} \
                                        New primary: {{ cluster_status_post.primary_node }} \
                                        Old secondary: {{ cluster_status_pre.secondary_node }} \
                                        New secondary: {{ cluster_status_post.secondary_node }}"
            test_case_details_from_test_case: {
                                        "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                        "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                        "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                        "Test Execution: Index Server Crash": "{{ index_server_result }}",
                                        "Post Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_post }}",
                                        "Post Validations: Validate HANA DB cluster status": "{{ cluster_status_post }}",
                                        }

    # /*---------------------------------------------------------------------------
    # |                          Post Validations                                 |
    # +--------------------------------------------------------------------------*/
    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"

  rescue:
    - name:                             "Rescue operation"
      ansible.builtin.include_tasks:    "roles/misc/tasks/rescue.yml"

- name:                                 "Pre Validations: Test Case Skipped"
  become:                               true
  when:                                 pre_validations_status == "FAILED"
  block:
    - name:                             "Set test case message and details"
      ansible.builtin.set_fact:
        test_case_message_from_test_case: "Pre Validations for HANA DB cluster status checks failed. Please check the details."
        test_case_details_from_test_case: {
                                          "Pre Validations: Remove any location_constraints": "{{ location_constraints_results }}",
                                          "Pre Validations: Validate HANA DB cluster status": "{{ cluster_status_pre }}",
                                          "Pre Validations: CleanUp any failed resource": "{{ cleanup_failed_resource_pre }}",
                                          "Cluster Status": "{{ cluster_status_pre }}",
                                        }

    - name:                             "Post Validations Tasks"
      ansible.builtin.include_tasks:    "roles/misc/tasks/post-validations.yml"
